version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/whisper-website:cached
      - whisper-models:/models            # ⬅️ volumen persistente para cachés de modelos
    command: sleep infinity
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      # ⬇️ rutas de caché dentro del volumen /models
      - WHISPER_CACHE_DIR=/models/whisper
      - HF_HOME=/models/hf
      - XDG_CACHE_HOME=/models/cache
  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  whisper-models: {}   # ⬅️ define el volumen
