"""init

Revision ID: 52717920826c
Revises: None
Create Date: 2025-09-28 16:49:36.423892
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # needed if autogen uses JSONB/UUID/ARRAY, etc.

# revision identifiers, used by Alembic.
revision = '52717920826c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('job',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ownerUserId', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('modelName', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('audioDurationMs', sa.Integer(), nullable=True),
    sa.Column('processingTimeMs', sa.Integer(), nullable=True),
    sa.Column('resultJsonPath', sa.String(), nullable=True),
    sa.Column('transcriptTxtPath', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('errorMessage', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ownerUserId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('assignedToUserId', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validFrom', sa.DateTime(), nullable=False),
    sa.Column('validUntil', sa.DateTime(), nullable=False),
    sa.Column('isRevoked', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignedToUserId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('file_artifact',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('jobId', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('sizeBytes', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jobId'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jobId', 'type', name='uix_job_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_artifact')
    op.drop_table('license')
    op.drop_table('job')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
